:- include('board').
:- include('game').
:- include('items').
:- include('movement').
:- include('looking').
:- include('inventory').
:- include('skills').
:- include('objects_usage').
:- include('status').